set anti
set guioptions=
set guifont=Noto\ Mono\ 9
set mousehide		" Hide the mouse when typing text
set vb t_vb=

" Reference line
hi ColorColumn guibg=DarkGrey

" Color scheme
colorscheme pencil

" Initial window size
win 101 45

if has('gui_macvim')
  set imdisable
  set transparency=10
endif

" vim:set et sw=2 ts=2:
