set nocompatible
filetype off

packadd vim-jetpack
call jetpack#begin()

Jetpack 'tani/vim-jetpack', {'opt': 1}

" Git wrapper
Jetpack 'tpope/vim-fugitive'

Jetpack 'tpope/vim-markdown'

" Buffer explorer
Jetpack 'jlanzarotta/bufexplorer'

" Cscope macro
"Jetpack 'cscope_macros.vim'

" Trailing white space
Jetpack 'bronson/vim-trailing-whitespace'

" Tag bar
Jetpack 'preservim/tagbar'

" Fancy status line
Jetpack 'vim-airline/vim-airline'
Jetpack 'vim-airline/vim-airline-themes'

" Easy cursor motion
Jetpack 'easymotion/vim-easymotion'

" File explorer
Jetpack 'preservim/nerdtree'

" Multiple highlights
"Jetpack 'inkarkat/vim-mark'

Jetpack 'editorconfig/editorconfig-vim'

" Session management
"Jetpack 'xolox/vim-misc'
"Jetpack 'xolox/vim-session'

" Alignment
Jetpack 'junegunn/vim-easy-align'

" Color schmes
Jetpack 'w0ng/vim-hybrid'
Jetpack 'NLKNguyen/papercolor-theme'
Jetpack 'reedes/vim-colors-pencil'
Jetpack 'udalov/kotlin-vim'
Jetpack 'haishanh/night-owl.vim'
Jetpack 'sheerun/vim-wombat-scheme'

call jetpack#end()
filetype plugin indent on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nobackup
set noswapfile
set showcmd
set showmatch
set ambiwidth=double
set wildmenu
set diffopt=internal,filler,algorithm:histogram,indent-heuristic

" Encodings/Formats
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,sjis,euc-jp,iso-2022-jp
set fileformats=unix,dos,mac

" Tab/Space settings
set et
set sw=4
set ts=4

" Indent
set autoindent
set cino=(0
set smartindent

" Display settings
set laststatus=2
set showtabline=2
set ruler
set shm+=I
set colorcolumn=80
hi ColorColumn ctermbg=LightGrey guibg=DarkGrey

" Search settings
set ignorecase
set smartcase
set incsearch
set hlsearch

" Cursor settings
set backspace=indent,eol,start
"set cursorline
set whichwrap=b,s,h,l

autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

autocmd BufWritePre * :FixWhitespace

syntax on

" Keymap
let mapleader = "\<Space>"
nnoremap <Esc><Esc> :noh<Return>
nnoremap j gj
nnoremap k gk
nnoremap <Leader>w :w<CR>
"nnoremap <C-n> :tabnext<CR>
"nnoremap <C-p> :tabprevious<CR>
map Q gq
cmap <C-x> <C-r>=expand('%:p:h')<CR>/

" Plugin settings
map <C-h> :NERDTreeToggle<CR>
"nmap <F8> :TagbarToggle<CR>

" ChangeLog settings
let g:changelog_username='Hiroo Ishikawa <hiroo.ishikawa@gmail.com>'

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
" vim:set et sw=2 ts=2:
